### ISSUE TITLE
Can we use the mod with custom model data?

### ISSUE THREAD

**Issue by titidelaff** [TheGreyGhost/ItemTransformHelper#13]
Can we use the mod with custom model data?
Or its only for vanilla item?

**Comment by TheGreyGhost** [comment]
Hi.  It should work for nearly all mods with custom model data.  The only items it doesn't work for is when the mod uses unusual rendering techniques for items, which is very rare.
-TGG

**Comment by titidelaff** [comment]
I ask the question because when I test the mod, I don't see the modifications on the items with a custom model data from my resource pack. I only see the changes for vanilla items
