### ISSUE TITLE
Perspective changing? 

### ISSUE THREAD

**Issue by Wyvern500** [TheGreyGhost/ItemTransformHelper#14]
Hello, sorry for my bad English, I have a question, for example if in a server I change the first person perspective of an item and another player has that same item, does it also change him?, thanks

**Comment by TheGreyGhost** [comment]
Hi
No it doesn't.  You would need to implement custom packets or a Capability if you wanted to achieve this.

Probably best to ask questions in this forum:
https://forums.minecraftforge.net/forum/70-modder-support/

They are very helpful and much quicker at answering than I am!

-TGG
