### ISSUE TITLE
1.16.5 support

### ISSUE THREAD

**Issue by GrigLog** [TheGreyGhost/ItemTransformHelper#15]
Please update to the latest version of mc, it should not take much effort.

**Comment by GrigLog** [comment]
Actually you just update forge and mappings versions in build.gradle and mods.toml and it works

**Comment by TheGreyGhost** [comment]
Cool thanks, I'll do that soon; I hadn't noticed that Forge had updated to 1.16.5.  Will update and test to make sure nothing has broken...
