### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by organnoise** [TheGreyGhost/ItemTransformHelper#4]
This is a stupid issue, but I have no idea how to install this. The instructions say to place the mod folder in MYPROJECT/eclipse/mods

I don't know which file is the one I should be putting in. I don't see any .jar file. Should I be?

**Comment by TheGreyGhost** [comment]
Just put the entire zip in there, don't unzip it.  When you run or debug your mod from Eclipse (or IntelliJ) Forge will load up the ItemTransformHelper mod as well.  If your steup doesn't have that folder, try a search for the mods folder in your project directory, that should show you where to put it.
