### ISSUE TITLE
It doesn't work anymore in forge 1.8-11.14.3.1502-2.0

### ISSUE THREAD

**Issue by a3626a** [TheGreyGhost/ItemTransformHelper#5]
Item Transform Helper draws its HUD, and also I can change the values. However the changes don't affect transformation of the item.

**Comment by a3626a** [comment]
is this log related to this problem?

[09:52:30] [Client thread/INFO] [ItemTransformHelper]: Warning - The Item Transform Helper replaces your IBakedModels with a wrapped version, this
[09:52:30] [Client thread/INFO] [ItemTransformHelper]:   is done even when the helper is not in your hotbar, and might cause problems if your
[09:52:30] [Client thread/INFO] [ItemTransformHelper]:   IBakedModel implements an interface ItemTransformHelper doesn't know about.
[09:52:30] [Client thread/INFO] [ItemTransformHelper]:   I recommend you disable the mod when you're not actively using it to transform your items.

**Comment by TheGreyGhost** [comment]
Hi
That's odd.  Is your item just an ordinary item?  Pls post a link to your item code?
The log warning is something the mod always prints just to warn folks that it messes with the registry to do its stuff.

I'll try it out again with the latest forge version, will take me a few days to get to it though, sorry :(

-TGG

**Comment by a3626a** [comment]
I think "public ItemCameraTransforms getItemCameraTransforms()" is completely deprecated in latest forge. Camera Transformation should be forced in "handlePerspective()". (in IPerspectiveAwareModel)

**Comment by ThexXTURBOXx** [comment]
Sorry for my late reply, but this bug still exists :(

**Comment by TheGreyGhost** [comment]
Hi, you're right.  I'm working on it, unfortunately there appears to be a bug in forge that stops one of the commands from working properly.  I'm trying to find a workaround but it involves quaternions and matrix math and it makes my teeth ache to wade through it.

In the meantime you can use an earlier release of forge to work around this problem (for example 1.8-11.14.1.1334).

**Comment by ThexXTURBOXx** [comment]
Ok, could you say me which command? I could help :D

**Comment by TheGreyGhost** [comment]
Dude that would be awesome :)

It's documented here:
https://github.com/MinecraftForge/MinecraftForge/issues/2425

**Comment by ThexXTURBOXx** [comment]
I will try to figure out what's going on there :)

**Comment by ThexXTURBOXx** [comment]
I just noticed, that the version number 1.8-11.14.3.1502-2.0 is wrong! It doesn't even work in 1.8-11.14.3.1501....

**Comment by ThexXTURBOXx** [comment]
Ok, but it works in Forge 1404... I don't know the exact version of forge causing that error, but it is between 1404 and 1487 (tested them)

**Comment by ThexXTURBOXx** [comment]
@TheGreyGhost Sorry, I know, that this is not the right place to message you, but I have a problem in modding. I saw you site, where you post explanations and tutorials. Nice work! Could you help me please?

**Comment by TheGreyGhost** [comment]
Hi 

After a lot of messing around I've managed to introduce a workaround that should work for all versions of Forge for Minecraft 1.8.

Pls try it out and let me know if it works for you, now?

Cheers
  TGG

**Comment by ThexXTURBOXx** [comment]
Oh, that's fantastic! I'll try that out in a few hours. :)

**Comment by ThexXTURBOXx** [comment]
Ok, I couldn't wait XD Tested it now, IT WORKS!
Nice work, man! Keep going ;) :+1:

**Comment by TheGreyGhost** [comment]
Keen  thanks dude  :)
