### ISSUE TITLE
Forge Universal Buckets

### ISSUE THREAD

**Issue by SirBlobman** [TheGreyGhost/ItemTransformHelper#6]
Forge Universal Buckets (which a lot of mods will use) cause a crash  with this mod

Crash http://pastebin.com/7iLzgukz
Forge: 1.10.2-12.18.1.2044

**Comment by TheGreyGhost** [comment]
Hmm you're right, that's annoying.  The bug is caused by an unsafe cast in the Forge code and I don't see  an easy way to work around it except to disable the transform tool for bucket models.  I'll have a play around to see what I can do.

**Comment by TheGreyGhost** [comment]
Do you have a test code with a bucket?
I think I've found a way to disable the transform for bucket models, but I'm not sure how to create a bucket model to test it with...

**Comment by SirBlobman** [comment]
You don't really register a model for them, it just does it. You can see my example code on how to create a Bucket in my Gemmary Mod

FluidRegistry.addBucketForFluid(registeredFluid);
https://github.com/SirBlobman/Gemmary/blob/master/1.10.2/src/java/com/SirBlobman/gemmary/fluid/GFluids.java

**Comment by TheGreyGhost** [comment]
Keen, thanks.
Actually, one of my other projects is a collections of examples on how to use different features of forge.  Would you mind if I adapted your fluid code and put into the project?  
-TGG

**Comment by SirBlobman** [comment]
Sure, I don't mind
One thing before you do that, your main class needs a method

`static {
        FluidRegistry.enableUniversalBucket();
    }`

**Comment by TheGreyGhost** [comment]
Hi Blobman
I've put a bugfix in place, would you mind testing it out for me?
The item transform helper won't alter the bucket appearance but at least it won't crash.

deobfuscated: 
https://www.dropbox.com/s/vi5n67hy74gser4/itemtransformhelper-1.10.2b-deobfuscated.jar?dl=0

normal:
https://www.dropbox.com/s/34c77kcdx3ezma5/itemtransformhelper-1.10.2b.jar?dl=0

-TGG

**Comment by SirBlobman** [comment]
It works! There's no JSON for forge buckets anyways, so being unable to alter them shouldn't be a problem
