### ISSUE TITLE
Compatibility with ItemOverrides

### ISSUE THREAD

**Issue by ThexXTURBOXx** [TheGreyGhost/ItemTransformHelper#7]
Hello again ;)
I wanted to override the textures of Vanilla Items using [diesieben007's tutorial](http://www.minecraftforge.net/forum/index.php/topic,40923.msg216008.html#msg216008).
Then I wanted to change the json-files using your Transform Helper, but it takes the vanilla-json-files, so I can't use the mod for my items (if you want, take my mod and try it: [Download](http://www.femtopedia.de/rusticohelper.jar)). With my mod installed, you have to take a stick and rename it (using an anvil) to "Crook". Now take a normal stick, the "Crook" and your camera in your hotbar. Now select the "Crook", press "Reset" and try to change the values. As you can see, the "Crook" won't change. Now take the normal stick, press "Reset" and try to change its values. It works perfectly.
If you want another example, take a Spider Web with my mod installed. Rename it to "Silk Mesh". Now try it with this item. It won't work, too :(
If you need my code, here it is: https://github.com/Rustico-Network/RusticoHelper
P.S.: I'm using Forge 1.10.2-12.18.1.2076

Thanks in advance
ThexXTURBOXx (Nico)

**Comment by TheGreyGhost** [comment]
Hi
Hmmm ok.  I will have a look.  Unfortunately it won't be quick, I have a lot of other things going on at the moment, so it might take several weeks until I get to it.
Instead of using RESET, you could try just changing the values to match what your modded item looks like, with a bit of practice it shouldn't be too hard.

Cheers
 TGG

**Comment by ThexXTURBOXx** [comment]
Hi,
the thing is, that the (modded) item doesn't rotate even when I change the values :/
Take your time ^^

ThexXTURBOx (Nico)
