### ISSUE TITLE
1.11 suport

### ISSUE THREAD

**Issue by dumptruckman** [TheGreyGhost/ItemTransformHelper#8]
Hi there. Any chance you wouldn't mind updating this mod for 1.11? Thank you!

**Comment by TheGreyGhost** [comment]
Hi
Yeah I'm planning to do it soon, there are a couple of things this mod needs that don't seem to be stable in Forge yet, hopefully they'll either be implemented soon or if not I'll spend some time working around them.  -TGG

**Comment by dumptruckman** [comment]
Awesome, thanks for the response!

**Comment by TheGreyGhost** [comment]
It currently works 100% except that print to console doesn't show anything in the Minecraft Game Output window.  I'm working on a fix.  The output can be found instead in logs\latest.log.  (Or, you can copy the values by hand).

https://www.dropbox.com/s/g9lcfhikbb6nge6/itemtransformhelper-1.11a.jar?dl=0
and
https://www.dropbox.com/s/ngnloxnewhhsoca/itemtransformhelper-1.11a-deobfuscated.jar?dl=0

**Comment by dumptruckman** [comment]
Wow, that was fast! Thanks a bunch.

**Comment by dumptruckman** [comment]
So it seems like the only item I can transform is the ItemCamera. If I have it in my hotbar and hold a different item, i can press Reset to see the values of the item I'm holding but any changes I make to them change the ItemCamera instead.

**Comment by TheGreyGhost** [comment]
hmm that's weird
I'll look into it in the next couple of days...

**Comment by TheGreyGhost** [comment]
Hi 
I tried to recreate the issue you're seeing, but it works fine for me.
Could you perhaps take a couple of screenshots or a short vid to show me what you're seeing?
Cheers  TGG
